//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#include "mui/mui.h"
#include "mui/controls.h"
#include <mui/ds_window.h>

class DewesoftBridge;

class BaseSetupWindow : public Dewesoft::MUI::DSWindow
{
public:

protected:
    DewesoftBridge& bridge;

    Dewesoft::MUI::CaptionPanel CreationPanel;
    Dewesoft::MUI::Label ipAddressLabel;
    Dewesoft::MUI::TextBox ipAddressTxtBox;
    Dewesoft::MUI::Label relayNumLabel;
    Dewesoft::MUI::TextBox relayNumTxtBox;
    Dewesoft::MUI::Label triggerChanneLabel;
    Dewesoft::MUI::ComboBox triggerChannelCBox;
    Dewesoft::MUI::Label edgeTypeLabel;
    Dewesoft::MUI::ComboBox edgeTypeCBox;
    Dewesoft::MUI::Label triggerLevelLabel;
    Dewesoft::MUI::TextBox triggerLevelTxtBox;
    Dewesoft::MUI::Button submitBtn;
    Dewesoft::MUI::CaptionPanel CurrentRelayPanel;
    Dewesoft::MUI::Button deleteBtn;
    Dewesoft::MUI::ListBox listBox;

    BaseSetupWindow(Dewesoft::MUI::WindowPtr& ui, DewesoftBridge& bridge, std::string pathToXmlFile) : DSWindow (ui, pathToXmlFile), bridge(bridge)
    {
        // connect class to UI controls
        CreationPanel = Dewesoft::MUI::CaptionPanel::Connect(ui, "CreationPanel");
        ipAddressLabel = Dewesoft::MUI::Label::Connect(ui, "ipAddressLabel");
        ipAddressTxtBox = Dewesoft::MUI::TextBox::Connect(ui, "ipAddressTxtBox");
        relayNumLabel = Dewesoft::MUI::Label::Connect(ui, "relayNumLabel");
        relayNumTxtBox = Dewesoft::MUI::TextBox::Connect(ui, "relayNumTxtBox");
        triggerChanneLabel = Dewesoft::MUI::Label::Connect(ui, "triggerChanneLabel");
        triggerChannelCBox = Dewesoft::MUI::ComboBox::Connect(ui, "triggerChannelCBox");
        edgeTypeLabel = Dewesoft::MUI::Label::Connect(ui, "edgeTypeLabel");
        edgeTypeCBox = Dewesoft::MUI::ComboBox::Connect(ui, "edgeTypeCBox");
        triggerLevelLabel = Dewesoft::MUI::Label::Connect(ui, "triggerLevelLabel");
        triggerLevelTxtBox = Dewesoft::MUI::TextBox::Connect(ui, "triggerLevelTxtBox");
        submitBtn = Dewesoft::MUI::Button::Connect(ui, "submitBtn");
        CurrentRelayPanel = Dewesoft::MUI::CaptionPanel::Connect(ui, "CurrentRelayPanel");
        deleteBtn = Dewesoft::MUI::Button::Connect(ui, "deleteBtn");
        listBox = Dewesoft::MUI::ListBox::Connect(ui, "listBox");
    }
};
